### ISSUE TITLE
SilentDefendersOfDeFi - Prevent Healing of Agents by price manipulation

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2023-10-looksrare-judging#139]
SilentDefendersOfDeFi

medium

# Prevent Healing of Agents by price manipulation
## Summary

A malicious user can prevent healing by manipulating uniswap V3 pool to make heal transactions revert. 
If the next round would include less then 50 agents, and some people are trying to heal there wounded agents, they will be unfairly killed.

## Vulnerability Detail

A user can submit heal requests to heal his wounded agents, the heal request will calculate the price of the heal and try to swap WETH into LOOKs token.
```solidity
IV3SwapRouter.ExactOutputSingleParams memory params = IV3SwapRouter.ExactOutputSingleParams({
            tokenIn: WETH,
            tokenOut: LOOKS,
            fee: POOL_FEE,
            recipient: address(this),
            amountOut: costToHealInLOOKS,
            amountInMaximum: msg.value,
            sqrtPriceLimitX96: 0
        });

``` 
The transaction will revert if the output is not large enough for heal.

Any malicious user can now manipulate the price of the uniswap pool by executing a large swap, and make heal transactions revert.

This will allow any attacker to prevent a user from healing his agents, 
for example if the user decides to heal his agents just before the next round in wich they would get killed.

He also can prevent other users from healing there agents if the next round would be the top 50 round. This will kill all wounded agents, even if they still could have healed.

In both cases this will cause unfair killing of agents.

## Impact

Unfair killings of agents by price manipulation.

## Code Snippet

https://github.com/sherlock-audit/2023-10-looksrare/blob/main/contracts-infiltration/contracts/InfiltrationPeriphery.sol#L45

## Tool used

Manual Review

## Recommendation
Give user the possibility to pay with own LOOK tokens/ let him execute swap on his own

Duplicate of #89

**Comment by Oot2k** [comment]
Escalate

I think this issue describes the impact of the price manipulation issue differently and thereby should be a valid medium.

The attack idea here is to make the heal swap revert by price manipulation to prevent healing and kill agents.

The difference here to other defi apps is that make a transaction revert can cause financial damage.
Think of following case:
User1 has 100 wounded agents, next round would be the last to heal them before they die.
User1 now waits till right before next round start and calls heal.
Attacker manipulates price.
User1s heal reverts, next round gets called and his agents die.

This attack is quite expensive, but the economical damage can be quite high, hence medium severity.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> I think this issue describes the impact of the price manipulation issue differently and thereby should be a valid medium.
> 
> The attack idea here is to make the heal swap revert by price manipulation to prevent healing and kill agents.
> 
> The difference here to other defi apps is that make a transaction revert can cause financial damage.
> Think of following case:
> User1 has 100 wounded agents, next round would be the last to heal them before they die.
> User1 now waits till right before next round start and calls heal.
> Attacker manipulates price.
> User1s heal reverts, next round gets called and his agents die.
> 
> This attack is quite expensive, but the economical damage can be quite high, hence medium severity.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by nevillehuang** [comment]
Hi @Oot2k, thanks for the detailed. Considering the following, I think this is a non-issue.

- Given the objective to prevent healing is to win the grand prize (which is not guaranteed), the cost of executing such a price manipulation is not incentivised.

- The recommendation that is Allowing users to heal directly using LOOKS is already possible via `Infiltration.heal()`. Users can always execute a swap via uniswap themselves where slippage can be applied or simply buy LOOKS off secondary exchanges. This say, heal will never revert due to price manipulation.

I think best is if you can provide a scenario where cost of attack for [manipulating this specific pool here](https://info.uniswap.org/#/pools/0x4b5ab61593a2401b1075b90c04cbcdd3f87ce011) to block healing is possibly more profitable for attacker than if he does not, then this finding could be reinstated. 

Though I think @0xhiroshi should take a look, happy to hear your thoughts.

**Comment by 0xhiroshi** [comment]
Are we talking about trying to manipulate the price of LOOKS using one's own capital over 2 transactions in the same block?
Can another bot come in to dump LOOKS to the inflated `WETH/LOOKS` pool before the attacker finishes the attack, after the heal reverts?

**Comment by nevillehuang** [comment]
Yes @Oot2k could you shed some more specific details on how the price manipulation could be performed?

**Comment by Oot2k** [comment]
@nevillehuang I agree with your second point raised. The user can indeed call the function on the contract it self without using the periphery contract.
I disagree with your fist point, sherlock rules state that even if attack is expensive / non profitable it still counts as medium.
I also believe even if the user can avoid this, this issue renders the periphery contract useless.

@0xhiroshi 
The attack would involve manipulating the price like you said, for example swaping a lot of WETH for LOOKs with would increase the price of LOOKs and make the transaction revert. After the attacker can swap LOOKs back to WETH.
He would use some form of MEV bot to avoid frontrunning.

In the end this is just a basic sandwich attack like all the other reports mention.

Here we just focused on the fact that the damage does not directly come from the price difference, but from the fact that a reverting transaction will cause financial damage by user losing his tokens (not healing).

The likelihood of this happening in real life is depending mainly on the size of price pool. If we assume that the price pool is 425 ETH (like the docs state), and current LOOKs volume does not increase significantly, this attack can become profitable if players with large stake in the game start attacking each other.

To summarize why I think this should be a medium:
- can be profitable if Token Price is high / a lot of participates in game
- renders the periphery contract useless

I don't think there can be done much about this issue -> mainly incurage users to not use swap when stakes are high.

**Comment by jpopxfile** [comment]
1. Users can swap using another aggregator or router and then heal directly.
2. Even if it fails, user can still heal anytime before the roundstart is called

**Comment by nevillehuang** [comment]
Hi @Oot2k considering the following I am on the fence of validating this issue as medium severity, but am leaning towards agreeing with you.

So i will state my points here and leave it up to @nasri136 @Evert0x for the final decision:

1. No fix can resolve this issue, unless protocol choose to remove the contract completely. Even if you implement a slippage, price manipulation will still cause `heal()` to revert.

2. On the other hand, somebody with sufficient funds can indeed potentially cause a permanent DoS of the `heal()` function assuming their "front-running bot" is capable enough to front-run all healing and they have sufficient capital to do so. The reason i brought up the profitability part is because sherlock rules also state this. From your submission I am finding it hard to picture how profitable price manipulation will be with regards to winning the grand prize, and I also understand if you find it hard to quantify it since it can be quite complex.

> The more expensive the attack is for an attacker, the less likely it will be included as a Medium (holding all other factors constant).

3. Like sponsor mentioned, the workaround is to self obtain LOOKS and perform the swap manually, in which case healing will never revert due to price manipulation

**Comment by Evert0x** [comment]
I don't think this is a valid issue.

It's the responsibility of the end user to acquire LOOKS at a good price. If the price of LOOKS would exponentially increase the minute before someone needs them, the person is paying the price for their urgent need to acquire LOOKS.

> renders the periphery contract useless

The periphery contract is function exactly like it's supposed to, as it reflects the market price.

**Comment by Czar102** [comment]
Result:
Invalid
Unique

Agree with Evert here, the details of the market price should not be considered here. Using a periphery contract to automatically acquire the LOOKS token is the responsibility of the user and is out of scope.

**Comment by sherlock-admin2** [comment]
The escalations could not be resolved because the issue failed the following checks:

- Expected unique issue. Actual duplicate of #89
