### ISSUE TITLE
enfrasico - Wrong use of VRF randomness can allow it to be exploited, allowing the exploiter to always win the game

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-10-looksrare-judging#80]
enfrasico

high

# Wrong use of VRF randomness can allow it to be exploited, allowing the exploiter to always win the game
## Summary
According to chainlink docs, ANY re-request of randomness is an incorrect use of the VRF https://docs.chain.link/vrf/v2/security#do-not-re-request-randomness

The current implementation allows for the random word to be requested again if there has been no response after 24 hours. This is a wrong usage of the VRF.

## Vulnerability Detail
This warning is taken from the chainlink docs

`Any re-request of randomness is an incorrect use of VRFv2. Doing so would give the VRF service provider the option to withhold a VRF fulfillment if the outcome is not favorable to them and wait for the re-request in the hopes that they get a better outcome, similar to the considerations with block confirmation time.`

This means that the VRF service provider, who can also be a player of the Infiltrator game, can withhold the random word if it is an unfavourable outcome, and re-roll the dice after 24 hours. 

Because the random word selects the agent to be wounded and determines if a heal is successful, if this agent happens to be the exploiter's, they can simply withhold the fulfillment, wait for 24 hours, and reroll it, and can repeat this until they get a good outcome. This gives the exploiter a sure-win condition. Their agent can never be wounded and their heal was always be successful, but heal is not needed since their agent will never be wounded to begin with. 

## Impact
Exploiter can exploit re-requesting of the VRF and guarantees a win.

## Code Snippet
https://github.com/sherlock-audit/2023-10-looksrare/blob/main/contracts-infiltration/contracts/Infiltration.sol#L575-L579

## Tool used

Manual Review

## Recommendation
Ensure that the randomness cannot be re-requested in all conditions.

Duplicate of #64

**Comment by Coareal** [comment]
Escalate

This is a serious critical issue that should be fixed by the protocol. To respond to the lead judge @nevillehuang on the validity of the issue,

First
> VRF provided randomness is trusted

The VRF provided randomness can be trusted if and only if it is used correctly. I have shown in the report how this is used incorrectly, allowing operators of the VRF to rig the randomness. This should not be a point to make this issue invalid. 

Second,
> Additionally, it is mentioned [here](https://github.com/sherlock-audit/2023-10-looksrare#q-are-the-admins-of-the-protocols-your-contracts-integrate-with-if-any-trusted-or-restricted) that external admins that LooksRare integrate with are trusted

But VRF operators are not any admins or trusted users of any contract we are integrating with. VRF operators are public. The admins of the contracts we are integrating with in this case would be chainlink admin, not VRF operators. 

Additionally, #48 and #131 should not be considered valid duplicates. Both has failed to show how the faulty randomness can result in the exploit.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> This is a serious critical issue that should be fixed by the protocol. To respond to the lead judge @nevillehuang on the validity of the issue,
> 
> First
> > VRF provided randomness is trusted
> 
> The VRF provided randomness can be trusted if and only if it is used correctly. I have shown in the report how this is used incorrectly, allowing operators of the VRF to rig the randomness. This should not be a point to make this issue invalid. 
> 
> Second,
> > Additionally, it is mentioned [here](https://github.com/sherlock-audit/2023-10-looksrare#q-are-the-admins-of-the-protocols-your-contracts-integrate-with-if-any-trusted-or-restricted) that external admins that LooksRare integrate with are trusted
> 
> But VRF operators are not any admins or trusted users of any contract we are integrating with. VRF operators are public. The admins of the contracts we are integrating with in this case would be chainlink admin, not VRF operators. 
> 
> Additionally, #48 and #131 should not be considered valid duplicates. Both has failed to show how the faulty randomness can result in the exploit. 
> 
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by nevillehuang** [comment]
I stand by my previous comments that VRF operators that are part of the DON are trusted external admins and that the protocol already deemed the outcome of VRF requests as trusted.

Besides, in this case the protocol is dependent on a “re-request” (it is really just a new separate request each round) to ensure a unique `randomWord` for every new round if not how will the game proceed? 

Suggest to keep invalid, I don’t have any additional comments to the above escalations so will leave it up to you guys for final decision @nasri136 @Evert0x

**Comment by Coareal** [comment]
Above commenter seems to not understand how VRF works. Each time `requestRandomWords` is called, we are awaiting for a callback from the VRF operator to receive our random word. The important point here is that before sending this callback, the VRF operator is able to see the results of the random word before they choose to send this callback. While they cannot arbitrarily decide the random word, they can re-roll the random word if it is not favourable for them, hence the warning in the chainlink docs.

**Comment by nasri136** [comment]
Hello @Coareal , as VRF provided randomness is trusted and VRF is set by owner of the contract who is trusted, in which scenario do you have a malicious VRF operator ?

**Comment by Coareal** [comment]
Hi @nasri136. I do understand the point of wanting to see every player as "trusted". But when the whole purpose of chainlink's VRF is for verifiable onchain tamper-proof results, I think this notion is misguided. We are integrating with chainlink, which in its documentation has a clear warning that any re-request implementation is incorrect, I fail to see how this is not a vulnerability. Hope you understand my point. Will leave it to you for the final decision.

**Comment by nasri136** [comment]
I agree that re-requesting is a clear warning from chainlink but here the one who requests a random number is the owner, who is trusted, so there is no vulnerability in this process from my point of view, am I wrong @Coareal ?

**Comment by Coareal** [comment]
Anyone can request a random number every 24 hours if there is no response. This itself is the vulnerability.

**Comment by nasri136** [comment]
From what I see on the code anyone can in fact call `startNewRound()` but `VRF_COORDINATOR`,`KEY_HASH` and `SUBSCRIPTION_ID` are immutable and set by owner of the contract who is trusted. So anyone can request a trusted setup to request a new random number , do you agree ?

**Comment by Coareal** [comment]
The issue isn't the request. The issue is the fulfilment of the request. The fulfilment is done by the `VRF_COORDINATOR` who we should not be trusting as warned by chainlink.

**Comment by nasri136** [comment]
So it comes to what said lead judge ,it falls into accepted risks as  "VRF provided randomness is trusted"

**Comment by Evert0x** [comment]
Planning to reject escalation and keep issue state as is because it falls into the accepted risks.

**Comment by Coareal** [comment]
Hi @nasri136, thanks for the ping. This will be my final comment. I am not sure how better I can explain the nuance in this issue and why "VRF provided randomness is trusted" is not applicable here. The random number generated from VRF is trusted - that is it cannot be selected in a way that is non random. The crux of the issue here however is that, even when working under the trust assumption that the random generator is random, it can be randomly selected **multiple times** when it is not in exploiter's favour.

**Comment by nevillehuang** [comment]
@Czar102 Be careful, if somebody can do that, better approach chainlink bug bounty first.

**Comment by PlamenTSV** [comment]
I agree with @Coareal, as I have stated the same in my finding, which is a dupe of this one. The chainlink docs specifically warn against such contract behavior because even if the service they provide is trusted, as in that the words they return are truly random, the mediator, aka the operator, is a 3rd party user who can choose if he should return the random word or not. Chainlink specifically lay out the possibility of having malicious VRF operators since they get to choose whether to wait for a new answer or not.
It is a historically valid anti-pattern, since even though yes Chainlink can slash malicious operators, they cannot predict if one will turn malicious given the chance. And that's exactly what happens, the contract is giving the provider a chance to cheat his chances which obviously is a flaw. You wouldn't play a game if you know somebody is able to cheat and get away with it.

**Comment by PlamenTSV** [comment]
Additionally, on the comment under my issue the accepted risks are mentioned with the line "admins from external protocols are also trusted". The VRF operator is not a trusted entity as it is susceptible to slashing thus it is seen as a possibly malicious actor, nor is he an admin. The trust assumption doesn't stand.

**Comment by nasri136** [comment]
Owner set the `VRF_COORDINATOR` within constructor so the only one able to cheat is set by someone trusted here

**Comment by nevillehuang** [comment]
@Czar102 @0xhiroshi you might want to take a look at this.

I side with @nasri136 on this one, given it explicitly mentioned the VRF provided randomness is trusted. But this issue again is eerily similar to #107 and #136, where watsons are arguing and finding loopholes against the clarity of the contest details. I have the same opinion as my [comment here](https://github.com/sherlock-audit/2023-10-looksrare-judging/issues/136#issuecomment-1806302547). 

This is getting increasingly frustrating as a judge in sherlock, given judges has a lot of issues to go through in such a short amount of time. I will give some feedback regarding this soon.

**Comment by 0xhiroshi** [comment]
imo this issue should be rejected as we have assumed the VRF randomness is to be trusted. You should also understand that VRF can be pending not just because the operator is malicious. For example, if the gas price is higher than our gas lane consistently, the game will be stuck. As a game we have to keep it running, and that's why we wanted to acknowledge issue #107 (we don't want the game to be stuck), but it should not be used as the reason to accept this issue. While we do have an emergency withdraw function to handle such situations, you need to understand the reputation damage that will cost our brand if we have to stop the game and that's why we would rather accept re-roll than to halt the game completely. We are **very** aware of the risk of chainlink VRF before we brought the code to Sherlock, and it has been mentioned in the README it's an acceptable risk. I wasn't clear about the OOG issue, but this one is very clear.

**Comment by PlamenTSV** [comment]
There are other services providing randomness, and easy solution to the anti-pattern would be to use a secondary one in case chainlinks response is late instead of rerequesting.

**Comment by Czar102** [comment]
> The crux of the issue here however is that, even when working under the trust assumption that the random generator is random, it can be randomly selected multiple times when it is not in exploiter's favour.

I think it is fair to agree with the watson that despite the randomness is trusted, the result may be not. But, external admins are trusted and according to @nasri136, the coordinator is a kind of admin (a whitelisted party with additional rights):

> Owner set the `VRF_COORDINATOR` within constructor so the only one able to cheat is set by someone trusted here so I think you would play a game if you trust the only one who is able to cheat

If this is true, I will be rejecting the escalation. @Coareal please let me know if this is the case.

**Comment by PlamenTSV** [comment]
The VRF COORDINATOR is the address of the service aka Chainlink, but the provider can be anybody. If you provide an address to a COORDINATOR and it's respective provider gets slashed by chainlink, you wouldn't need to change the COORDINATOR. So no, it is not a trusted party.

**Comment by Czar102** [comment]
@PlamenTSV could you back up those claims by a link to the docs? Would also appreciate a relevant quote.

**Comment by PlamenTSV** [comment]
"Chainlink VRF (Verifiable Random Function) is a provably fair and verifiable random number generator (RNG) that enables smart contracts to access random values without compromising security or usability. For each request, Chainlink VRF generates one or more random values and cryptographic proof of how those values were determined. The proof is published and verified on-chain before any consuming applications can use it. This process ensures that results cannot be tampered with or manipulated by any single entity including oracle operators, miners, users, or smart contract developers."
This is what the README mentions as VRF **randomness** being trusted, as it is that the number really is random.

"VRFCoordinatorV2Interface COORDINATOR: The address of the Chainlink VRF Coordinator contract that this contract will use. Initialized in the constructor."
"address vrfCoordinator: The address of the Chainlink VRF Coordinator contract."
The coordinator is just a contract executing a set of instructions, it is not an entity that can be granted a trust assumption

"Any re-request of randomness is an incorrect use of VRFv2. Doing so would give the VRF service provider the option to withhold a VRF fulfillment if the outcome is not favorable to them and wait for the re-request in the hopes that they get a better outcome, similar to the considerations with block confirmation time.
Re-requesting randomness is easily detectable on-chain and should be avoided for use cases that want to be considered as using VRFv2 correctly."
This is the elephant in the room, which with the help of the above 2 quotes, facilitates the fact that you do not get to choose your VRF service provider, thus you cannot grant him trust even if you wished to.
Off-chain mechanism generates randomness -> VRF service provider accepts it and passes it to the coordinator -> coordinator sends the random words to your subscribed contract. The provider withholds the answers, randomness is re-requested, he rigs the game.

The relevant links are:
https://docs.chain.link/vrf/v2/security/#do-not-re-request-randomness
https://docs.chain.link/vrf
https://docs.chain.link/vrf/v2/getting-started - go to the Contract Variables section

**Comment by Czar102** [comment]
My question was about the identity of providers, sorry for not being specific. Can you prove that I can join the providers set and rig the game?

**Comment by PlamenTSV** [comment]
https://chain.link/faqs - What is a node operator (serving the purpose of a provider)
In quote form: "Node operators within the Chainlink Network strictly adhere to the best security practices and use external monitoring systems to ensure a secure and reliable operation is maintained around the clock. Third-party marketplaces like [market.link](https://market.link/) provide users insight into the current and historical performance of each individual node operator. <ins>**Additionally, anybody can become a Chainlink node operator and immediately begin providing smart contracts access to offchain data. If you are interested in running a node, please navigate to our [documentation](https://docs.chain.link/docs/running-a-chainlink-node).**</ins>"
Also I think the VRF security considerations outline the obvious fact that providers aren't to be trusted entities and my previous comment proves the fact that the COORDINATOR != provider, thus no, the protocol does NOT choose who gives them data, so the trust assumption doesn't hold.

**Comment by Czar102** [comment]
I see. So the operator, which may withhold the data, is neither:
- a whitelisted party, hence can't be considered an admin
- a provider of randomness, but acts as a relayer.

Then I don't see good grounds to invalidate this issue. @0xhiroshi could you look at it again?

**Comment by nasri136** [comment]
from my point of view that false, being a chainlink node and having the possibility to provide random number does not give you the power to "withhold" a request, providers are incentivised to provide random number , this is the same process for a miner if you have a node but don't provide a block you won't get paid and another miner will do the job for you
So this process you mentioned is false
```
Off-chain mechanism generates randomness -> VRF service provider accepts it and passes it to the coordinator -> coordinator sends the random words to your subscribed contract. The provider withholds the answers, randomness is re-requested, he rigs the game.
```
provider cannot withholds something he just provides so if one of the providers does not provide a random number, another one will do the job **as they are incentivised to do that**

**Comment by Czar102** [comment]
That would mean there is an exploit in the VRF where you could withhold randomness in order to "retry the chances", right?

**Comment by PlamenTSV** [comment]
It's a literal statement that is a confirmed security flaw in the VRF docs. The provider CAN withhold sending the value to the coordinator.
a whitelisted party, hence can't be considered an admin
a provider of randomness, but acts as a relayer.
These 2 points by @Czar102 are exactly correct and are the entire issue we are escalating and wish to validate this finding.
Also @nasri136's comment is wrong, as the miners have the ability to withhold a block, there are multiple articles covering that. Once assigned to a block, the miner chooses his verification, this is why the EVM-compatible chains do not have a constant block time. And they can get slashed, since they are not 100% trusted parties.
And these points are valid 100% for VRF providers aswell - withholding, waiting for a re-request, getting slashed upon detected abuse, no trust-assumption. It is exactly the fact they can rig their game the vulnerability we want validated.

**Comment by jpopxfile** [comment]
Unlike most games that play round by round, where we can invalidate a round if the VRF request is not fulfilled within a reasonable time, this game requires the VRF to be fulfilled for the game to continue. It would not be acceptable to end the game just because 1 round's VRF is not fulfilled beyond 24 hours.

The only other solution suggested here is to use a second source of randomness, but this would require some change to the implementation, and if that's the case, we might as well not use VRF and go with another source of randomness instead.

Due to the design of the game and how it requires randomness to proceed, and how the game should not be prematurely ended if the VRF is not fulfilled, we have stated this to be an accepted risk in the competition brief.

**Comment by Czar102** [comment]
The protocol team gets to choose the keyhash for the randomness, which is provided by Chainlink itself. This makes the provider Chainlink, which is a party whitelisted by the protocol team (~admin). Hence the issue is out of scope and invalid.

**Comment by Czar102** [comment]
Result:
Invalid
Duplicate of #64

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [Coareal](https://github.com/sherlock-audit/2023-10-looksrare-judging/issues/80/#issuecomment-1805160354): rejected
